python ../train/train.py -m F_init_from_pretrained -d F_middle_0 -e 100 --learning-rate 1e-3 -s 10 -o F_pretrained_on_middle_0 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_0 -d F_middle_1 -e 100 --learning-rate 8e-4 -s 50 -o F_pretrained_on_middle_1 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_1 -d F_middle_2 -e 100 --learning-rate 6e-4 -s 50 -o F_pretrained_on_middle_2 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_2 -d F_middle_3 -e 100 --learning-rate 5e-4 -s 50 -o F_pretrained_on_middle_3 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_3 -d F_middle_4 -e 100 --learning-rate 3e-4 -s 50 -o F_pretrained_on_middle_4 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_4 -d F_middle_5 -e 100 --learning-rate 2e-4 -s 50 -o F_pretrained_on_middle_5 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_5 -d F_middle_6 -e 100 --learning-rate 1e-4 -s 50 -o F_pretrained_on_middle_6 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_6 -d F_middle_7 -e 100 --learning-rate 8e-5 -s 50 -o F_pretrained_on_middle_7 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_7 -d F_middle_8 -e 100 --learning-rate 7e-5 -s 50 -o F_pretrained_on_middle_8 -t Normal -b 1 --no-valid True
python ../train/train.py -m F_pretrained_on_middle_8 -d F_middle_9 -e 100 --learning-rate 4e-5 -s 50 -o F_pretrained_on_middle_9 -t Normal -b 1 --no-valid True
